---
title: "Consumo Eléctrico de Vivienda en Nuevo León"
author: 
    - name: Guillermo Barrios
      email: gbv@ier.unam.mx
    - name: Erick Romo
      email: roelej@ier.unam.mx 
    - name: Octavio Molina
    - name: Alexis Levy
    - name: Fairuz Loutfi
      email: fairuz.loutfi@wri.org
author-title: "Autores"  
lang: es
bibliography: biblio.bib
format: 
    html:
        embed-resources: true
        toc: true           # ←-- habilita la tabla de contenido
        toc-title: "Índice" # título que aparecerá encima del TOC
        toc-depth: 3        # (opcional) niveles de encabezado que se mostrarán
        number-sections: true   # (opcional) numeración automática de secciones
    docx:                    # ← aquí definimos la salida para Word
        toc: true              # tabla de contenido
        number-sections: true  # numeración de secciones
    pdf:                    # ← aquí definimos la salida para Word
        toc: true              # tabla de contenido
        number-sections: true  # numeración de secciones
    # opcional: reference-doc: "plantilla.docx"


notebook-links: false
---

# Resumen ejecutivo
Este documento se presentan los datos de consumo eléctrico de la vivienda del estado de Nuevo León. Los datos provienen de la ENCEVI 2018 y representan a 1,427,843 viviendas.

# Consumos totales en vivienda con y sin aire acondicionado

Del total de viviendas en Nuevo León el 43.8% cuenta con aire acondicionado (AA) y son responsables del 50.8% del consumo energético. La vivienda sin aire acondicionado representa al 56.2% con un 49.5% del consumo del sector.


| Uso de AA          |   Viviendas (%) |   Consumo (%) |
|:-------------------|----------------:|--------------:|
| Con AA             |          43.8 |       50.8      |
| Sin AA             |          56.2 |       49.2      |

: Uso o no uso de aire acondicionado (AA), porcentaje de viviendas y porcentaje de consumo total en Nuevo León.

# Consumo por tipología y estrato socioeconómico en vivienda con y sin uso de aire acondicionado

Para cada grupo de vivienda (con y sin uso de AA) se calcula el porcentaje de consumo relativo respecto a cada grupo.

## Consumo con aire acondicionado

|   Tipología ($m^2$) | Estrato socioeconómico  |  % del consumo total      | % de viviendas |
|-----:|:-----------|--------------------:|----------------:|
|  100 | Medio alto |                 5.4 |             6.7 |
|  100 | Alto       |                 4.1 |             6.2 |
|  150 | Alto       |                 3.7 |             4.5 |
|  150 | Medio alto |                 2.8 |             4.2 |
|  200 | Alto       |                 2.7 |             2   |
|  150 | Medio bajo |                 2.7 |             2.4 |
|  100 | Medio bajo |                 2.6 |             4.1 |
|   75 | Medio alto |                 2.5 |             3.1 |
|  200 | Medio alto |                 2.4 |             2.5 |
|   75 | Medio bajo |                 1.3 |             2.7 |
|   55 | Medio bajo |                 1.3 |             1.8 |
|  200 | Medio bajo |                 0.9 |             0.6 |
|   75 | Alto       |                 0.8 |             1.2 |
|  100 | Bajo       |                 0.3 |             0.3 |
|   55 | Alto       |                 0.2 |             0.5 |
|   55 | Medio alto |                 0.2 |             0.5 |
|   75 | Bajo       |                 0.1 |             0.3 |
|  200 | Bajo       |                 0.1 |             0.1 |
|   55 | Bajo       |                 0   |             0.2 |

: Porcentaje de consumo total respecto al grupo de vivienda con aire acondicionado por tipología y estrato socioeconómico.

 

## Consumo sin aire acondicionado

|   Tipología ($m^2$) | Estrato socioeconómico  |  % del consumo total      | % de viviendas |
|-----:|:-----------|--------------------:|----------------:|
|  100 | Medio alto |                 4.4 |             7.9 |
|  100 | Medio bajo |                 4.2 |             7.5 |
|   75 | Medio bajo |                 3.3 |             6.4 |
|  150 | Medio bajo |                 2.9 |             4.8 |
|   55 | Medio bajo |                 2.4 |             4.2 |
|  200 | Medio alto |                 2.3 |             2.7 |
|  150 | Medio alto |                 2.2 |             3.7 |
|  200 | Medio bajo |                 2   |             2.2 |
|  100 | Alto       |                 1.7 |             2.9 |
|   75 | Medio alto |                 1.6 |             3.7 |
|  150 | Alto       |                 1.3 |             1.9 |
|   55 | Medio alto |                 1.3 |             1.8 |
|   75 | Alto       |                 0.9 |             1.6 |
|  200 | Alto       |                 0.5 |             1.3 |
|   30 | Medio bajo |                 0.5 |             1.4 |
|   75 | Bajo       |                 0.4 |             0.6 |
|  100 | Bajo       |                 0.1 |             0.3 |
|  150 | Bajo       |                 0.1 |             0.2 |
|   55 | Alto       |                 0.1 |             0.2 |
|   55 | Bajo       |                 0.1 |             0.4 |
|   30 | Medio alto |                 0.1 |             0.2 |
|   30 | Bajo       |                 0   |             0.2 |


: Porcentaje de consumo total respecto al grupo de vivienda sin aire acondicionado por tipología y estrato socioeconómico.
